# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-09-27 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('text', models.TextField(blank=True, max_length=255)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('usertoken', models.CharField(blank=True, db_column='userToken', max_length=255, null=True)),
                ('blogid', models.CharField(blank=True, db_column='blogId', max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('updatetime', models.DateTimeField(blank=True, db_column='updateTime', null=True)),
                ('id', models.AutoField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'blog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogid', models.CharField(blank=True, db_column='blogId', max_length=255, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'collection',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('date', models.DateTimeField(blank=True, null=True)),
                ('commentscontent', models.CharField(blank=True, db_column='commentsContent', max_length=255, null=True)),
                ('blogid', models.CharField(blank=True, db_column='blogId', max_length=255, null=True)),
                ('id', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('commentstoken', models.CharField(blank=True, db_column='commentsToken', max_length=255, null=True)),
            ],
            options={
                'db_table': 'comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Replycomments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replytext', models.CharField(blank=True, db_column='replyText', max_length=255, null=True)),
                ('replydate', models.DateTimeField(blank=True, db_column='replyDate', null=True)),
                ('commentsid', models.CharField(blank=True, db_column='commentsId', max_length=255, null=True)),
                ('totoken', models.CharField(blank=True, db_column='toToken', max_length=255, null=True)),
                ('fromtoken', models.CharField(blank=True, db_column='fromToken', max_length=255, null=True)),
                ('blogid', models.CharField(blank=True, db_column='blogId', max_length=255, null=True)),
            ],
            options={
                'db_table': 'replycomments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('sex', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('headimg', models.CharField(blank=True, db_column='headImg', max_length=255, null=True)),
                ('background', models.CharField(blank=True, max_length=255, null=True)),
                ('registerdate', models.DateTimeField(blank=True, db_column='registerDate', null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
